### ISSUE TITLE
Amethyst Gem Lighting Glitch

### ISSUE THREAD

**Issue by TheToimeWulf** [gryttr/KAGIC#5]
![2017-09-11_21 09 06](https://user-images.githubusercontent.com/31873444/30307902-d97e94ae-973e-11e7-90cd-174d4befe6c1.png)
[Image above is of 6 Amethysts, half of which experienced this glitch]

[Found on KAGIC 1.10.0 A1, 11/9/2017]

This glitch appears to happen after Amethysts are poofed and reform on the ground naturally. There is no determinable factor causing this glitch, nor evidence that this happens to other gems as I tested.

This glitch tends to correct itself within 15 seconds to one minute after the Amethyst reforms, and happens usually rarely. Please note that the image above is of a completely new world and that there are no lighting blocks within 30 blocks of the Amethysts.

**Comment by Akrivus** [comment]
> [Found on KAGIC 1.10.0 A1, 11/9/2017]

Why are you using A1 when you're from two months in the future? Just kidding.
This is not a glitch, but an Amethyst in her triggered state. All quartz gems have this behavior, which has been utilized since KAGIC v0.8, explained:
- Amethysts bear this behavior when hit a specific amount of times, they will create chain lightning.
- Jaspers are reverse, the more they hit, the more they are triggered, they induce a gravity attack.
- Carnelians, like Amethysts, need to get hit, and generate widespread explosions.
- Rose Quartzes create melon heads.
- Rubies, while not quartzes, bear similar behavior where their fire powers intensify.
